### ISSUE TITLE
UnicodeDecodeError on binary values

### ISSUE THREAD

**Issue by jaraco** [whit537/mongs#28]
In the latest codebase, I'm getting this error querying a document.

```
Traceback (most recent call last):
  File "/app/.heroku/venv/lib/python2.7/site-packages/algorithm.py", line 288, in run
    new_state = function(**deps.as_kwargs)
  File "/app/.heroku/venv/lib/python2.7/site-packages/aspen/algorithms/website.py", line 115, in get_response_for_resource
    return {'response': resource.respond(state)}
  File "/app/.heroku/venv/lib/python2.7/site-packages/aspen/http/resource.py", line 59, in respond
    content_type, body = super(Dynamic, self).respond(accept, state)
  File "/app/.heroku/venv/lib/python2.7/site-packages/aspen/simplates/__init__.py", line 180, in respond
    body = render(context)
  File "/app/.heroku/venv/lib/python2.7/site-packages/aspen/simplates/renderers/__init__.py", line 150, in __call__
    return self.render_content(context)
  File "/app/.heroku/venv/lib/python2.7/site-packages/aspen_jinja2_renderer.py", line 66, in render_content
    return self.compiled.render(context).encode(charset)
  File "/app/.heroku/venv/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/app/.heroku/venv/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/app/www/%server/%database/%collection/%filter/%page.int/index.html.spt", line 1, in top-level template code
    """Spaghetti! Who likes spaghetti? It's mildly documented spaghetti, at least.
  File "/app/base.html", line 131, in top-level template code
    {% block content %}{% endblock %}
  File "/app/www/%server/%database/%collection/%filter/%page.int/index.html.spt", line 37, in block "content"
    v = '%s (%s)' % (v, v.generation_time)
  File "/app/www/%server/%database/%collection/%filter/%page.int/index.html.spt", line 247, in generate_pairs
    pair = Pair(base, _id, k, v)
  File "/app/www/%server/%database/%collection/%filter/%page.int/index.html.spt", line 54, in __init__
    v = v.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd4 in position 0: ordinal not in range(128)
500 Internal Server Error            /localhost/gryphon-us/cases/{"region": "US", "questionnaire_name": "G4_test_JR_gridint"}/1/ ...s/aspen/www/error.spt
```

**Comment by jaraco** [comment]
I'm trying to understand how a replace operation could cause a UnicodeDecodeError on Python 2. I wonder if the upgrade to Aspen 0.42 causes the simplate Python block to be executed with `__future__.unicode_literals`.

**Comment by jaraco** [comment]
Indeed, if I `print(repr(v)); print(repr('&'))` at that place, I get:

```
Binary("\xd4\x9b\xfb<\xe9)f\xa3\x7f\x8e\xf1(\x8b\xb3\xbb\x06\x9dW\xa6\xb2\x14V\x98\xe2\xd7[Y\t\xb3\xf6\xdf+[\xdc\x0bKy\n\x8b\xcdSu@\xcc\xbdO|\x8e\xe2\xf3\xb2\xf0\xdb\xd4\xc5\xb0\x8am\xba\xe3\x12\xda\xa0\xd6\xa5\xce\xc7\xb6\x81\xcf\xa16\t\xad^\x06}@\xc5\n\x88\xd3\x91\x83r\x1d\x0f\xa1[x\xdb\x0c\xf1u\xa7\xd6\xff\xc2V'\xdfM\xe3P\x9aiX\xd6\x8a\xc9Vq\x86\xa3\xd1Q\xae~\xfdsFG\x9d\x14M\x9fN\xdcW\xba\x8f\xef\x99\t\x8frj\xd7\xb5\x97\x9e\xe9\xb4\xee\xd9\x80\xb7Z\x19u", 0)
u'&'
```

Seems that the changes to Pymongo and Aspen have cause binary values to no longer render.
